# Домашнее задание по программированию: Линейная алгебра: сходство текстов и аппроксимация функций

### Задание 1. Сравнение предложений

In [1]:
import pandas as pd
import re
import scipy.spatial
import numpy as np

In [2]:
def cleanup(file):
    sentences = file.readlines()
    list_sent = []
    for sentence in sentences:
        sentence = re.split('[^a-z]', sentence.lower())
        sentence = list(filter(None,sentence))
        list_sent.append(sentence)
    return list_sent

In [3]:
def count(senten):
    word_index = dict()
    index = 0
    for sentence in list_sent:
        #print(sentence)
        for word in sentence:
            if word not in word_index:
                word_index[word] = index
                index += 1
    return word_index

In [4]:
def math(list_sent, word_index):
    matrix_list = []
    for sent_num in range(len(list_sent)):
        matrix_list.append([0 for x in word_index])
        for word in list_sent[sent_num]:
            word_num = word_index[word]
            matrix_list[sent_num][word_num] += 1
            
    matrix = np.array(matrix_list)
    distances = list()
    for i in range(len(list_sent)):
        distance = scipy.spatial.distance.cosine(matrix[0], matrix[i])
        distances.append((i, distance))
        
    sorted_list = sorted(distances, key=lambda x: x[1])
    #submission = [sorted_list[1][0], sorted_list[2][0]]
    #print(submission)
    with open('submission-1.txt', 'w', encoding='utf-8') as f:
        f.write('%.f %.f' % (sorted_list[1][0], sorted_list[2][0]))

In [5]:
with open('sentences.txt', 'r', encoding='utf16') as file:
    list_sent = cleanup(file)
    word_index = count(list_sent)
    math(list_sent, word_index)

### Задание 2. Аппроксимация функции

f(x) = sin(x / 5) * exp(x / 10) + 5 * exp(-x / 2)

In [6]:
import scipy.linalg
from numpy import sin, exp
import numpy as np

In [7]:
function = lambda x: sin(x / 5.0) * exp(x / 10.0) + 5 * exp(-x / 2.0)

In [8]:
def experiment1():
    rank1 = 1
    M1 = [
        [1 ** n for n in range(rank1 + 1)],
        [15 ** n for n in range(rank1 + 1)]
    ]
    
    V1 =  [function(1), function(15)]
    return scipy.linalg.solve(M1, V1)

In [9]:
def experiment2():
    rank2 = 2
    M2 = [
        [1 ** n for n in range(rank2 + 1)],
        [8 ** n for n in range(rank2 +1)],
        [15 ** n for n in range(rank2 + 1)]
    ]
    
    V2 =  [function(1), function(8), function(15)]
    return scipy.linalg.solve(M2, V2)

In [10]:
def experiment3():
    rank3 = 3
    M3 = [
        [1 ** n for n in range(rank3 + 1)],
        [4 ** n for n in range(rank3 + 1)],
        [10 ** n for n in range(rank3 +1)],
        [15 ** n for n in range(rank3 + 1)]
    ]
    
    V3 =  [function(1), function(4), function(10), function(15)]
    return np.round(scipy.linalg.solve(M3, V3), 2)

In [11]:
experiment1()

array([ 3.43914511, -0.18692825])

In [12]:
experiment2()

array([ 3.32512949, -0.06531159, -0.00760104])

In [13]:
experiment3()

array([ 4.36, -1.3 ,  0.19, -0.01])